export const ALL_PRODUCT_REQUESTS = 'ALL_PRODUCT_REQUESTS'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAILED = 'ALL_PRODUCT_FAILED'
// ---------------------------------------------------------------------
export const PRODUCT_DETAILS_REQUESTS = 'ALL_PRODUCT_REQUESTS'
export const PRODUCT_DETAILS_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const PRODUCT_DETAILS_FAILED = 'ALL_PRODUCT_FAILED'

export const CLEAR_ERROR = 'CLEAR_ERROR'